[build]
  base = "chorus"
  command = "npm install && npm run build"
  publish = "chorus/dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
